repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.21
    hooks:
      - id: uv-lock
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [--fix]
  - repo: local
    hooks:
      - id: ty
        name: ty check
        pass_filenames: false
        entry: |
            uvx ty@0.0.8 check
            --extra-search-path /opt/ros/humble/lib/python3.10/site-packages
            --extra-search-path /opt/ros/humble/local/lib/python3.10/dist-packages
        language: system