#!/usr/bin/bash

if [ "$#" -eq 0 ]
then
  echo "Usage: $0 <path/to/inventory.yml>"
  exit 1
fi

inventory="$1"


if [ ! -f ~/.ssh/id_rsa.pub ]
then
  ssh-keygen
fi

function copy_id_if_online() {
  local ip="$1"
  ping -c1 -W1 "$ip" > /dev/null && ssh-copy-id "$ip" || echo "$ip is unreachable, skipping."
}

export -f copy_id_if_online
grep "ansible_host" "$inventory" | awk '{print $2;}' | xargs -L1 -I {} bash -c 'copy_id_if_online "{}"'

uv run pproxy -l http://:7171 &
pproxy_pid=$!
uv run ansible-playbook -f10 --ask-become-pass -i "$inventory" ansible/install_workers.yml 
kill $pproxy_pid
