#!/usr/bin/bash

if [ "$#" -eq 0 ]
then
  echo "Usage: $0 <path/to/inventory.yml>"
  exit 1
fi

inventory="$1"

uv run pproxy -l http://:7171 &
pproxy_pid=$!
uv run ansible-playbook -f10 --ask-become-pass -i "$inventory" ansible/install_workers.yml 
kill $pproxy_pid