site_name: SYNC.TOOLING
repo_url: https://github.com/tier4/sync_tooling
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Integrators' Guide: 
    - integrators-guide.md
    - ***REMOVED*** gen2: integrators-guide/***REMOVED***.md
  - Design: design.md
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
plugins: 
  - search
  - macros:
      module_name: scripts/mkdocs_macros
  - drawio
  - autorefs
  - api-autonav:
      modules:
        - sync_tooling_msgs/src/sync_tooling_msgs
        - diag_master/src/diag_master
        - diag_worker/src/diag_worker
        - sync_graph/src/sync_graph
        - pmc_monitor/src/pmc_monitor
        - linuxptp_monitor/src/linuxptp_monitor
        - journal_monitor/src/journal_monitor
        - ros2_transport/src/ros2_transport
      nav_section_title: "API Reference"
      api_root_uri: "reference" 
      nav_item_prefix: "<code class='doc-symbol doc-symbol-nav doc-symbol-module'></code>"
      exclude_private: true
  - section-index
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
            - https://typing-extensions.readthedocs.io/en/latest/objects.inv
          options:
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_style: google
            docstring_section_style: list
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: false
            separate_signature: true
            show_bases: true
            show_inheritance_diagram: false
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            signature_crossrefs: true
            summary: true
extra_javascript:
  - js/drawio-reload.js
