sonar.organization=tier4
sonar.projectKey=tier4_sync_tooling

sonar.python.version=3.10
sonar.python.xunit.reportPath=pytest-results.xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff.json
sonar.sources=sync_tooling_msgs/src,diag_worker/src,journal_monitor/src,pmc_monitor/src,diag_master/src,sync_graph/src,linuxptp_monitor/src,http_transport/src
sonar.tests=sync_tooling_msgs/tests,pmc_monitor/tests,sync_graph/tests