sonar.organization=tier4
sonar.projectKey=tier4_sync_tooling

sonar.python.version=3.10
sonar.python.xunit.reportPath=pytest-results.xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff.json