[project]
name = "diag-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Max SCHMELLER", email = "max.schmeller@tier4.jp" }
]
requires-python = ">=3.10"
dependencies = [
    "flask-api>=3.1",
    "flask>=3.1.0",
    "http-transport",
    "sync-graph",
]

[project.scripts]
diag-master = "diag_master.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/diag_master"]

[tool.uv.sources]
http-transport = { workspace = true }
sync-graph = { workspace = true }
