[project]
name = "diag-master"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Max SCHMELLER", email = "max.schmeller@tier4.jp" }
]
requires-python = ">=3.10"
dependencies = [
    "flask-api>=3.1",
    "flask>=3.1.0",
    "sync-graph",
    "sync-tooling-msgs",
    "pyyaml>=6.0.2",
    "flask-socketio>=5.5.1",
    "pydot>=3.0.4",
]

[project.scripts]
diag-master = "diag_master.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/diag_master"]

[tool.uv.sources]
sync-graph = { workspace = true }
sync-tooling-msgs = { workspace = true }
