[project]
name = "pmc_monitor"
version = "0.1.0"
description = "A package for monitoring local and remote PTP nodes by implementing a PTP Management Client."
authors = [{ name = "Max Schmeller", email = "max.schmeller@tier4.jp" }]
dependencies = [
    "pytest>=8.3.4",
]

[project.scripts]
pmc-monitor = "pmc_monitor.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
