- name: Package Python Project
  hosts: localhost
  tasks:
    - name: Update project dependencies
      ansible.builtin.command:
        cmd: uv sync --all-packages
      args:
        chdir: "{{ lookup('env', 'PWD') }}"
      changed_when: true
    
    - name: Test the project for issues
      ansible.builtin.shell:
        cmd: uvx ruff check && uv run pytest
      args:
        chdir: "{{ lookup('env', 'PWD') }}"

    - name: Generate `requirements.txt`
      ansible.builtin.command:
        cmd: uv export --no-hashes --all-packages --no-emit-workspace --no-dev -o /tmp/requirements.txt
      args:
        chdir: "{{ lookup('env', 'PWD') }}"
      changed_when: true

    - name: Package the current directory with `uv build`
      ansible.builtin.command:
        cmd: uv build
      args:
        chdir: "{{ lookup('env', 'PWD') }}"
      changed_when: true
    
    - name: Find the built wheel file
      ansible.builtin.find:
        paths: "{{ lookup('env', 'PWD') }}/dist"
        patterns: "*.whl"
        use_regex: false
      register: wheel_file

    - name: Ensure exactly one wheel file was built
      ansible.builtin.fail:
        msg: "Expected exactly one wheel file in the dist directory."
      when: wheel_file.files | length != 1

    - name: Save the wheel file path
      ansible.builtin.set_fact:
        wheel_path: "{{ wheel_file.files[0].path }}"

- name: Deploy and Test Application
  hosts: all
  vars:
    apt_requirements_file: apt-requirements.txt
    # Set the control node (node running the playbook) to be the proxy for nodes not connected to internet
    proxy: "http://{{ ansible_env.SSH_CONNECTION.split(' ')[0] }}:7171"
    venv_path: "/opt/sync_diagnostics/.venv"
  environment:
    all_proxy: "{{ proxy }}"
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  tasks:
    - name: Debug proxy
      ansible.builtin.debug:
        var: to_debug
      vars:
        to_debug:
          proxy: "{{proxy}}"
          connection: "{{ ansible_env.SSH_CONNECTION }}"

    - name: Copy the wheel file to target nodes
      ansible.builtin.copy:
        src: "{{ hostvars['localhost'].wheel_path }}"
        dest: "/tmp/"
        mode: '644'

    - name: Copy the wheel file to target nodes
      ansible.builtin.copy:
        src: "/tmp/requirements.txt"
        dest: "/tmp/"
        mode: '644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 7200  # 2 hours
      become: true
    
    - name: Check if Python 3.10 is present
      ansible.builtin.command:
        cmd: python3.10 -m pip --version
      register: python_check
      failed_when: false
      changed_when: false

    - name: Install Python 3.10
      when: python_check.rc != 0
      block:
        - name: Add PPA dependencies
          ansible.builtin.apt:
            name: 
              - software-properties-common
            state: present
          become: true

        - name: Add deadsnakes PPA key
          ansible.builtin.shell:
            cmd:  curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF23C5A6CF475977595C89F51BA6932366A755776" | sudo apt-key add
          become: true

        - name: Add deadsnakes PPA
          ansible.builtin.apt_repository:
            repo: ppa:deadsnakes/ppa
            state: present
          become: true

        - name: Install Python 3.10
          ansible.builtin.apt:
            name: 
              - python3.10 
              - python3.10-venv 
              - python3.10-dev 
              - python3-apt
            state: present
            update_cache: yes
          become: true

    - name: Install extra apt dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ lookup('file', lookup('env', 'PWD') + '/' + apt_requirements_file).splitlines() }}"
      when: apt_requirements_file is file
      become: true
    
    - name: Install virtualenv
      ansible.builtin.apt:
        name: python3-virtualenv
      become: true


    - name: Configure venv
      block:
        - name: Reset venv
          ansible.builtin.command:
            cmd: rm -rf "{{ venv_path }}"
          become: true

        - name: Create venv
          ansible.builtin.command:
            cmd: virtualenv --python python3.10 "{{ venv_path }}"
          become: true
        
        - name: Install pip
          ansible.builtin.shell:
            cmd: . {{ venv_path }}/bin/activate && (curl -sS https://bootstrap.pypa.io/get-pip.py | python)
          become: true
    
    - name: Install sync tooling
      block:
        - name: Install wheel's requirements
          ansible.builtin.shell:
            cmd: . {{ venv_path }}/bin/activate && pip install -r /tmp/requirements.txt
          become: true

        - name: Install the wheel file
          ansible.builtin.shell:
            cmd: . {{ venv_path }}/bin/activate && pip install --force-reinstall /tmp/{{ hostvars['localhost'].wheel_path | basename }}
          become: true
    
    - name: Configure systemd services
      block:
        - name: Install Sync Diagnostcs Master
          ansible.builtin.template:
            src: templates/sync_diag_master.service.j2
            dest: /etc/systemd/system/sync_diag_master.service
            group: root
            owner: root 
            mode: 0644
          when: sync_master is defined
          register: install_sync_master
          become: true
        
        - name: Install Sync Diagnostcs Worker
          ansible.builtin.template:
            src: templates/sync_diag_worker.service.j2
            dest: /etc/systemd/system/sync_diag_worker.service
            group: root
            owner: root 
            mode: 0644
          when: sync_worker is defined
          register: install_sync_worker
          become: true
        
        - name: Reload systemd daemon
          ansible.builtin.systemd_service:
            daemon_reload: true
          when: (install_sync_worker is changed) or (install_sync_master is changed)
          become: true
        
        - name: Enable and run master
          ansible.builtin.systemd_service:
            name: sync_diag_master
            enabled: true
            state: restarted
          when: not (install_sync_master is skipped)
          become: true

        - name: Enable and run worker
          ansible.builtin.systemd_service:
            name: sync_diag_worker
            enabled: true
            state: restarted
          when: not (install_sync_worker is skipped)
          become: true
