all:
  vars:
    remote_user: autoware
  hosts:
    main:
      ansible_host: 192.168.20.11
      sync_worker:
        ptp4l_units:
          - ptp4l@enp3s0
          - ptp4l@vlan.500
          - ptp4l_hw_timestamp@vlan.500
        phc2sys_units:
          - phc2sys_sys_to_enp3s0
          - phc2sys_sys_to_enp5s0f0
      sync_master:
        reference: ../diag_master/config/x2gen2.yml
    sub:
      ansible_host: 192.168.20.21
      sync_worker:
        ptp4l_units:
          - ptp4l@enp3s0
          - ptp4l@enp5s0f0
        phc2sys_units:
          - phc2sys_enp5s0f0_to_sys
          - phc2sys_enp5s0f0_to_enp3s0
    perception1:
      ansible_host: 192.168.20.31
      sync_worker:
        ptp4l_units:
          - ptp4l
        phc2sys_units: []
    perception2:
      ansible_host: 192.168.20.32
      sync_worker:
        ptp4l_units:
          - ptp4l
        phc2sys_units: []
    addon:
      ansible_host: 192.168.20.33
      sync_worker:
        ptp4l_units:
          - ptp4l
        phc2sys_units: []
    logging:
      ansible_host: 192.168.20.71
      sync_worker:
        ptp4l_units:
          - ptp4l
        phc2sys_units: []
    ms1:
      ansible_host: 192.168.20.61
      sync_worker:
        ptp4l_units:
          - ptp4l  # currently not set up
        phc2sys_units: []
    ms2:
      ansible_host: 192.168.20.62
      sync_worker:
        ptp4l_units:
          - ptp4l  # currently not set up
        phc2sys_units: []
    signage:
      ansible_host: 192.168.20.41
      sync_worker:
        ptp4l_units:
          - ptp4l
        phc2sys_units: []
    voice-system:
      ansible_host: 192.168.20.51
      sync_worker:
        ptp4l_units:
          - ptp4l
        phc2sys_units: []
