[project]
name = "diag-worker"
version = "0.2.11"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Max SCHMELLER", email = "max.schmeller@tier4.jp" }]
requires-python = ">=3.10"
dependencies = [
    "aiostream>=0.6.4",
    "linuxptp_monitor",
    "pmc_monitor",
    "sync-tooling-msgs",
    "ros2-transport",
]

[project.scripts]
diag-worker = "diag_worker.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/diag_worker"]

[tool.uv.sources]
sync-tooling-msgs = { workspace = true }
ros2-transport = { workspace = true }
