clock_tree:
  main-ecu.sys:
    main-ecu.ptp0:
      other-ecu.ptp0:
        other-ecu.sys:
      sensor@radar/front:
    main-ecu.ptp1:
      sensor@lidar/left:
      sensor@lidar/right:
diagnostics:
  diff_thresholds:
    ptp_master:
      warn: 100
      error: 1000
      unit: us
    phc2sys:
      warn: 100
      error: 1000
      unit: us
    measurement:
      warn: 1
      error: 20
      unit: ms
