# This workflow will install Python dependencies, run tests, lint and upload the results to SonarQube.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# This name shows up in status badges, so a concise one is better.
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.10
          python-version: 3.10
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev --all-packages
      - name: Lint with Ruff
        run: |
          uvx ruff check --output-format=github .;
          uvx ruff check --output-file=ruff.json --output-format=json .
      - name: Test with pytest
        if: success() || failure()
        run: |
          uv run pytest --cov --cov-report=xml --junit-xml=pytest-results.xml
      - name: SonarQube Scan
        if: success() || failure()
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docs:
    runs-on: ubuntu-22.04
    steps: []
