# This workflow builds and publishes documentation to GitHub pages

name: docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  UV_VERSION: "0.5.10"
  PYTHON_VERSION: "3.10"

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev --all-packages
      - name: Build docs
        run: |
          uv run mkdocs gh-deploy --strict --force